on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - dev
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY: ${{secrets.API_KEY}}
          envkey_RAT: ${{secrets.RAT}}
          envkey_BASIC_URL: ${{secrets.BASIC_URL}}
          envkey_BASIC_IMAGE_URL: ${{secrets.BASIC_IMAGE_URL}}
          envkey_YT_VDO_URL: ${{secrets.YT_VDO_URL}}
      - uses: subosito/flutter-action@v2.7.1
        with:
          flutter-version: "3.0.5"
          channel: "stable"
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Release
        uses: ncipollo/release-action@v1.11.0
        with:
          artifacts: "build/app/outputs/flutter-apk/*,build/ios/iphoneos/app.ipa"
          tag: v1.5.${{github.run_number}}
          token: ${{secrets.TOKEN}}
